### ISSUE TITLE
Doesn't return matching songs 

### ISSUE THREAD

**Issue by kexo1** [jjoeldaniel/genius.py#9]
**Bug:**
I search for song by using genius.search() and inputting title of song in it (for example "The Weeknd - Blinding Lights"), but i get different results

**Code:**
```
genius = GeniusBuilder(client_access_token='token')
song = genius.search("The Weeknd - Blinding Lights")
for _ in song:
    print(_)
```

**Returns:**
The Weeknd Rolling Stones Interview by The Weeknd
Boogie Nights Screenplay by Paul Thomas Anderson
Liner Notes: Kendrick Lamar, To Pimp a Butterfly (2015) by Brandon Terry (Ft. Hiphop Archive and Research Institute)
Brandon Terry by To Pimp a Butterfly Test Liner Note
The 10 Most Influential Slam Dunks of All Time by Daudi Abe
In Tribute: The Complete, Untold Story of Slayer's Jeff Hanneman by Slayer (Ft. Guitar World)
Friday Night Pyro (February 14th, 2020) by XPWEW
2023 Listening Log by WhoIsTiz
Big Red Son by David Foster Wallace
Ride Around Shining by Chris Leslie-Hynan

**Info:**
Package version: 0.9.0
OS: Windows 10

**Comment by jjoeldaniel** [comment]
Thanks for opening this issue, will be looked into soon.

**Comment by jjoeldaniel** [comment]
I can't seem to reproduce this. Using `genius.py` I get the following output.

```
Blinding Lights by The Weeknd
The Weeknd - Blinding Lights (Traducción al Español) by Genius Traducciones al Español
The Weeknd - Blinding Lights (Türkçe Çeviri) by Genius Türkçe Çeviri
Blinding Lights (Chromatics Remix) by The Weeknd (Ft. Chromatics)
The Weeknd - Blinding Lights (Deutsche Übersetzung) by Genius Deutsche Übersetzungen
The Weeknd - Blinding Lights (Русский перевод) by Genius Russian Translations (Русские переводы)
The Weeknd - Blinding Lights (Nederlandse Vertaling) by Genius Nederlandse Vertalingen
The Weeknd - Blinding Lights (Traduction Française) by Genius Traductions françaises
The Weeknd - Blinding Lights (Polskie Tłumaczenie) by Polskie tłumaczenia Genius
The Weeknd - Blinding Lights (Svensk Översättning) by Genius Swedish Translations
```

Using the [interactive docs](https://docs.genius.com/#search-h2), I also receive the same output. 

Are you able to test this again?

**Comment by kexo1** [comment]
I still get same results, it might be token issue or different country,

Do i need to have some kind of premium genius account?

This also happens when using LyricsGenius package and i have no idea why

**Comment by jaasonw** [comment]
can confirm, i also get the same results 

```
Blinding Lights by The Weeknd
The Weeknd - Blinding Lights (Traducción al Español) by Genius Traducciones al Español
The Weeknd - Blinding Lights (Türkçe Çeviri) by Genius Türkçe Çeviri
Blinding Lights (Chromatics Remix) by The Weeknd (Ft. Chromatics)
The Weeknd - Blinding Lights (Deutsche Übersetzung) by Genius Deutsche Übersetzungen
The Weeknd - Blinding Lights (Русский перевод) by Genius Russian Translations (Русские переводы)
The Weeknd - Blinding Lights (Nederlandse Vertaling) by Genius Nederlandse Vertalingen
The Weeknd - Blinding Lights (Traduction Française) by Genius Traductions françaises
The Weeknd - Blinding Lights (Polskie Tłumaczenie) by Polskie tłumaczenia Genius
The Weeknd - Blinding Lights (Svensk Översättning) by Genius Swedish Translations
```

it might be some sort of locality issue? does the same issue appear when you search on the actual website?
https://genius.com/search?q=The%20Weeknd%20-%20Blinding%20Lights

**Comment by kexo1** [comment]
![IMG_8520](https://github.com/jjoeldaniel/genius.py/assets/115703948/903b183f-a0d5-43da-a01c-79f8b8bca230)
No, i have correct results

**Comment by jjoeldaniel** [comment]
> I still get same results, it might be token issue or different country,
> 
> Do i need to have some kind of premium genius account?
> 
> This also happens when using LyricsGenius package and i have no idea why

No, you do not need a premium account for API usage. This could be a locality issue, did the [interactive docs](https://docs.genius.com/#search-h2) return the same broken result?

**Comment by kexo1** [comment]
These are top 3 results i get by using docs, second one is what i want

`{
[+](https://docs.genius.com/#)meta: {...},
[-](https://docs.genius.com/#)response: {
[-](https://docs.genius.com/#)hits: [
[-](https://docs.genius.com/#) {
[+](https://docs.genius.com/#)highlights: [...],
index: "song",
type: "song",
[-](https://docs.genius.com/#)result: {
annotation_count: 1,
api_path: "/songs/801214",
artist_names: "Pearl and the Beard",
full_title: "The Lament of Coronado Brown by Pearl and the Beard",
header_image_thumbnail_url: "https://images.genius.com/4dbbf9e3a8d67e212b09eff2b3b328d5.300x300x1.jpg",
header_image_url: "https://images.genius.com/4dbbf9e3a8d67e212b09eff2b3b328d5.1000x1000x1.jpg",
id: 801214,
lyrics_owner_id: 1549345,
lyrics_state: "complete",
path: "/Pearl-and-the-beard-the-lament-of-coronado-brown-lyrics",
pyongs_count: null,
relationships_index_url: "https://genius.com/Pearl-and-the-beard-the-lament-of-coronado-brown-sample",
[+](https://docs.genius.com/#)release_date_components: {...},
release_date_for_display: "May 10, 2011",
release_date_with_abbreviated_month_for_display: "May. 10, 2011",
song_art_image_thumbnail_url: "https://images.genius.com/4dbbf9e3a8d67e212b09eff2b3b328d5.300x300x1.jpg",
song_art_image_url: "https://images.genius.com/4dbbf9e3a8d67e212b09eff2b3b328d5.1000x1000x1.jpg",
[+](https://docs.genius.com/#)stats: {...},
title: "The Lament of Coronado Brown",
title_with_featured: "The Lament of Coronado Brown",
url: "https://genius.com/Pearl-and-the-beard-the-lament-of-coronado-brown-lyrics",
[+](https://docs.genius.com/#)featured_artists: [...],
[+](https://docs.genius.com/#)primary_artist: {...}
}
},,`


,`
[-](https://docs.genius.com/#) {
[+](https://docs.genius.com/#)highlights: [...],
index: "song",
type: "song",
[-](https://docs.genius.com/#)result: {
annotation_count: 10,
api_path: "/songs/5049949",
artist_names: "The Weeknd",
full_title: "Blinding Lights by The Weeknd",
header_image_thumbnail_url: "https://images.genius.com/0b32bf010a7361676426365480c5cce8.300x300x1.jpg",
header_image_url: "https://images.genius.com/0b32bf010a7361676426365480c5cce8.1000x1000x1.jpg",
id: 5049949,
lyrics_owner_id: 8117646,
lyrics_state: "complete",
path: "/The-weeknd-blinding-lights-lyrics",
pyongs_count: 273,
relationships_index_url: "https://genius.com/The-weeknd-blinding-lights-sample",
[+](https://docs.genius.com/#)release_date_components: {...},
release_date_for_display: "November 29, 2019",
release_date_with_abbreviated_month_for_display: "Nov. 29, 2019",
song_art_image_thumbnail_url: "https://images.genius.com/22ca9d47b12db20bbfc88da431fba87b.300x300x1.png",
song_art_image_url: "https://images.genius.com/22ca9d47b12db20bbfc88da431fba87b.1000x1000x1.png",
[+](https://docs.genius.com/#)stats: {...},
title: "Blinding Lights",
title_with_featured: "Blinding Lights",
url: "https://genius.com/The-weeknd-blinding-lights-lyrics",
[+](https://docs.genius.com/#)featured_artists: [...],
[+](https://docs.genius.com/#)primary_artist: {...}
}
},,`


,`
[-](https://docs.genius.com/#) {
[+](https://docs.genius.com/#)highlights: [...],
index: "song",
type: "song",
[-](https://docs.genius.com/#)result: {
annotation_count: 8,
api_path: "/songs/5062494",
artist_names: "Genius Traducciones al Español",
full_title: "The Weeknd - Blinding Lights (Traducción al Español) by Genius Traducciones al Español",
header_image_thumbnail_url: "https://images.genius.com/aa1f027e5730d62263934e4b938d8040.300x300x1.jpg",
header_image_url: "https://images.genius.com/aa1f027e5730d62263934e4b938d8040.750x750x1.jpg",
id: 5062494,
lyrics_owner_id: 8876412,
lyrics_state: "complete",
path: "/Genius-traducciones-al-espanol-the-weeknd-blinding-lights-traduccion-al-espanol-lyrics",
pyongs_count: 2,
relationships_index_url: "https://genius.com/Genius-traducciones-al-espanol-the-weeknd-blinding-lights-traduccion-al-espanol-sample",
[+](https://docs.genius.com/#)release_date_components: {...},
release_date_for_display: "November 29, 2019",
release_date_with_abbreviated_month_for_display: "Nov. 29, 2019",
song_art_image_thumbnail_url: "https://images.genius.com/aa1f027e5730d62263934e4b938d8040.300x300x1.jpg",
song_art_image_url: "https://images.genius.com/aa1f027e5730d62263934e4b938d8040.750x750x1.jpg",
[+](https://docs.genius.com/#)stats: {...},
title: "The Weeknd - Blinding Lights (Traducción al Español)",
title_with_featured: "The Weeknd - Blinding Lights (Traducción al Español)",
url: "https://genius.com/Genius-traducciones-al-espanol-the-weeknd-blinding-lights-traduccion-al-espanol-lyrics",
[+](https://docs.genius.com/#)featured_artists: [...],
[+](https://docs.genius.com/#)primary_artist: {...}
}
},`
